name: Run build

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4

            # Install Python
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

              # Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  make install

            - name: Install Xvfb and required libraries
              run: |
                  sudo apt-get update
                  sudo apt-get install -y xvfb libx11-dev libxext-dev libxrender-dev libxtst-dev libxi-dev

            # Start the virtual display in order to be able to start app.

            # Finally run
            - name: Run Application and Exit After Launch
              run: |
                  # Start a virtual display
                  Xvfb :99 -screen 0 1024x768x16 &
                  export DISPLAY=:99

                  # Run the application in the background
                  python main.py &
                  APP_PID=$!

                  # Wait for the application to initialize
                  sleep 5

                  # Check if the application is running successfully
                  if ps -p $APP_PID > /dev/null; then
                      echo "Application launched successfully. Exiting."
                      kill $APP_PID
                  else
                      echo "Application failed to launch."
                      exit 1
                  fi
                  
            # Run unit tests
            - name: Run Unit Tests
              run: |
                  export DISPLAY=:99
                  python -m unittest discover -s tests -p "*.py"
