name: Run build and tests

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Check out the repository
            - uses: actions/checkout@v4

            # Install Python
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            # Install dependencies
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  make install

            # Install Xvfb and required libraries
            - name: Install Xvfb and required libraries
              run: |
                  sudo apt-get update
                  sudo apt-get install -y xvfb libx11-dev libxext-dev libxrender-dev libxtst-dev libxi-dev

            # Start the virtual display
            - name: Start Xvfb
              run: |
                  Xvfb :99 -screen 0 1024x768x16 &
                  export DISPLAY=:99

            # Run the application to verify it launches correctly
            - name: Run Application and Exit After Launch
              run: |
                  # Start the app in the background
                  python main.py &
                  APP_PID=$!

                  # Wait for the app to initialize
                  sleep 5

                  # Verify app launch
                  if ps -p $APP_PID > /dev/null; then
                      echo "Application launched successfully. Exiting."
                      kill $APP_PID
                  else
                      echo "Application failed to launch."
                      exit 1
                  fi

            # Run unit tests
            - name: Run Unit Tests
              run: |
                  export DISPLAY=:99
                  python -m unittest discover -s tests -p "*.py"
